#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : astunparse
Version  : 1.6.2
Release  : 20
URL      : https://files.pythonhosted.org/packages/f4/f4/e3e126cfea7dbf802d8610115beac62f4baaff55c40614442844b4efe0d6/astunparse-1.6.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/f4/f4/e3e126cfea7dbf802d8610115beac62f4baaff55c40614442844b4efe0d6/astunparse-1.6.2.tar.gz
Summary  : An AST unparser for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: astunparse-license = %{version}-%{release}
Requires: astunparse-python = %{version}-%{release}
Requires: astunparse-python3 = %{version}-%{release}
Requires: six
Requires: wheel
BuildRequires : buildreq-distutils3
BuildRequires : py
BuildRequires : pytest
BuildRequires : testtools
BuildRequires : wheel

%description
AST Unparser
        ============

%package license
Summary: license components for the astunparse package.
Group: Default

%description license
license components for the astunparse package.


%package python
Summary: python components for the astunparse package.
Group: Default
Requires: astunparse-python3 = %{version}-%{release}

%description python
python components for the astunparse package.


%package python3
Summary: python3 components for the astunparse package.
Group: Default
Requires: python3-core

%description python3
python3 components for the astunparse package.


%prep
%setup -q -n astunparse-1.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550689299
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/astunparse
cp LICENSE %{buildroot}/usr/share/package-licenses/astunparse/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/astunparse/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
