#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : astunparse
Version  : 1.5.0
Release  : 13
URL      : https://pypi.python.org/packages/1a/b7/3ba7ce33cbc8847e20ed1a4fbec2303a71b2512dec0194824e8dcaadc8de/astunparse-1.5.0.tar.gz
Source0  : https://pypi.python.org/packages/1a/b7/3ba7ce33cbc8847e20ed1a4fbec2303a71b2512dec0194824e8dcaadc8de/astunparse-1.5.0.tar.gz
Summary  : An AST unparser for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: astunparse-python3
Requires: astunparse-license
Requires: astunparse-python
Requires: six
Requires: wheel
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : testtools

%description
AST Unparser
        ============

%package license
Summary: license components for the astunparse package.
Group: Default

%description license
license components for the astunparse package.


%package python
Summary: python components for the astunparse package.
Group: Default
Requires: astunparse-python3

%description python
python components for the astunparse package.


%package python3
Summary: python3 components for the astunparse package.
Group: Default
Requires: python3-core

%description python3
python3 components for the astunparse package.


%prep
%setup -q -n astunparse-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530326172
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/astunparse
cp LICENSE %{buildroot}/usr/share/doc/astunparse/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/astunparse/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
